field: c6fb33da-e3f0-4f50-a4c5-4cce12415e80 # Scoops
fieldLayouts:
  7ae7f9a6-a9e1-4ba4-84f7-23006bebf1ca:
    tabs:
      -
        elements:
          -
            fieldUid: 071aeb2b-e8eb-4bcf-825c-dd016745f107 # Flavor
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8f804a45-ad1d-4a71-b0b4-6df2040dc205 # Nuts
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6359fe58-db81-4ee6-94eb-e9f4e3c61da6 # Notes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  8f804a45-ad1d-4a71-b0b4-6df2040dc205: # Nuts
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: nuts
    instructions: ''
    name: Nuts
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Nuts
            -
              - value
              - nuts
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  071aeb2b-e8eb-4bcf-825c-dd016745f107: # Flavor
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: flavor
    instructions: ''
    name: Flavor
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: false
      source: null
      sources:
        - 'section:10571998-751e-449a-98c5-d48adf32034b' # Flavors
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  6359fe58-db81-4ee6-94eb-e9f4e3c61da6: # Notes
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: notes
    instructions: ''
    name: Notes
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: default
name: default
sortOrder: 1
