field: ade97714-e4c4-4c73-9322-2c6b398cef04 # Colors Swatches
fieldLayouts:
  3e2f89e1-55db-41e9-8815-5a9a167a7940:
    tabs:
      -
        elements:
          -
            fieldUid: 1f716763-7f9e-4ffd-9f8c-2c0e7ccf15f7 # Selected
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f652db8c-edc2-4a66-8241-2fb0787110ee # Primary Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4828c563-32cf-4021-afeb-1d5e38f31daf # Accent Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1f716763-7f9e-4ffd-9f8c-2c0e7ccf15f7: # Selected
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: selected
    instructions: ''
    name: Selected
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  4828c563-32cf-4021-afeb-1d5e38f31daf: # Accent Color
    columnSuffix: null
    contentColumnType: string(7)
    fieldGroup: null
    handle: accentColor
    instructions: ''
    name: 'Accent Color'
    searchable: false
    settings:
      defaultColor: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
  f652db8c-edc2-4a66-8241-2fb0787110ee: # Primary Color
    columnSuffix: null
    contentColumnType: string(7)
    fieldGroup: null
    handle: primaryColor
    instructions: ''
    name: 'Primary Color'
    searchable: false
    settings:
      defaultColor: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Color
handle: default
name: default
sortOrder: 1
